print "automation session name is here 1"
print "https://example.com/path-to-public-url-1"
print "automation session name is here 2"
print "https://example.com/path-to-public-url-2"
print "automation session name is here 3"
print "https://example.com/path-to-public-url-3"
