---
version: 2
jobs:
  shellcheck:
    docker:
      - image: koalaman/shellcheck:stable
    working_directory: /mnt
    steps:
      - checkout
      - run:
          name: Shellcheck
          command: shellcheck /mnt/bin/*
  test:
    docker:
      - image: uetomae/automata-stage:latest
    working_directory: /var/autotest/automata
    parallelism: 1
    steps:
      - checkout
      - run:
          name: Run test automata itself
          command: bats ./test
workflows:
  version: 2
  test:
    jobs:
      - shellcheck
      - test
