---
version: 2
jobs:
  shellcheck:
    docker:
      - image: nlknguyen/alpine-shellcheck:latest
    steps:
      - checkout
      - run:
          name: Shellcheck
          command: |
            find ./bin -type f | wc -l
            find ./bin -type f | xargs shellcheck
  test:
    docker:
      - image: uetomae/automata-stage:latest
    working_directory: /var/autotest/automata
    parallelism: 1
    steps:
      - checkout
      - run:
          name: Run test automata itself
          command: bats ./test
workflows:
  version: 2
  test:
    jobs:
      - shellcheck
      - test
