---
version: 2
jobs:
  test:
    docker:
      - image: uetomae/automata-stage:latest
    working_directory: /var/autotest/automata
    parallelism: 1
    steps:
      - checkout
      - run:
          name: Run test automata itself
          command: bats ./test
workflows:
  version: 2
  test:
    jobs:
      - test
